# Generated by Django 2.1.15 on 2020-10-28 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='iamge',
            new_name='image',
        ),
    ]
